### ISSUE TITLE
Please bump release

### ISSUE THREAD

**Issue by donbowman** [ypid/ansible-kernel_module#1]
I think you have already reworked the metadata for the ansigenome issue. But ansible galaxy has 1.0 as the version number, and that is pre your metadata change.

It would be helpful to bump the release # to allow ansible galaxy to pull a newer version, and thus to work w/ ansible 2.0+

**Comment by ypid** [comment]
Done. Thanks for the reminder :+1: I don’t use Galaxy much for my Ansible setup currently.

**Comment by donbowman** [comment]
i think it will still prefer the v1.0 one from july 28 rather than the new 0.3 one.

**Comment by ypid** [comment]
Ah, thanks. I already made the 1.0 release :smile: Fixed: https://galaxy.ansible.com/ypid/kernel_module/
