### ISSUE TITLE
remove rolename's "ansible-" prefix

### ISSUE THREAD

**Issue by mbergumi** [ypid/ansible-kernel_module#4]
breaks the documentation and naming convention
installation is actually working with: 
`ansible-galaxy install debops-contrib.ansible-kernel_module`

**Comment by ypid** [comment]
Thanks for reporting! I had similar problems with other roles on Galaxy before and thought I had fixed all of them. Seems I have overlooked one.

Fixed: https://github.com/debops-contrib/ansible-kernel_module
